#!/usr/bin/bash

check_cluster_connectivity__() {
    if ! kubectl cluster-info &> /dev/null; then
        echo -e "${RED}[✖]${NC} Access to cluster not successful. Network issue or cluster unreachable. "
        exit 1
    else
        echo -e "${GREEN}[✓]${NC} Access to cluster successful. Cluster is reachable."
    fi
}

check_cluster_connectivity_snipp() {
    local message="$1"
    local command="$2"

    local pid
    local delay=0.1
    local spin='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏'
    local i=0

    echo -n "⠿ $message... "
    bash -c "$command" &>/dev/null &
    pid=$!

    # Spinner loop
    while kill -0 $pid 2>/dev/null; do
        i=$(( (i+1) % ${#spin} ))
        printf "\r%s %s..." "${spin:$i:1}" "$message"
        sleep $delay
    done

    wait $pid
    exit_code=$?

    if [ $exit_code -eq 0 ]; then
        printf "\r${GREEN}[✓] %s... done${NC}\n" "$message"
        #print_separator
    else
        printf "\r${RED}[✖] %s... failed${NC}\n" "$message"
        exit 1
    fi
}

check_cluster_connectivity() {
    check_cluster_connectivity_snipp "Checking cluster connectivity" "timeout 10 kubectl cluster-info"
}
